/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;
import content.gestionAdherent;
import content.gestionDocument;
import content.statistique;
import java.awt.Color;
/**
 *
 * @author Hp
 */
public class acceuil extends javax.swing.JFrame {

    gestionAdherent a = new gestionAdherent();

    
    public acceuil() {
        initComponents();
        main.add(a);
        a.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gDocButt = new javax.swing.JButton();
        AccButton = new javax.swing.JButton();
        gAdherButt = new javax.swing.JButton();
        statsButt = new javax.swing.JButton();
        decButt = new javax.swing.JButton();
        main = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(49, 119, 115));

        gDocButt.setBackground(new java.awt.Color(255, 255, 204));
        gDocButt.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        gDocButt.setText("gestion document");
        gDocButt.setBorder(new javax.swing.border.MatteBorder(null));
        gDocButt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gDocButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gDocButtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gDocButtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gDocButtMouseReleased(evt);
            }
        });
        gDocButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gDocButtActionPerformed(evt);
            }
        });

        AccButton.setBackground(new java.awt.Color(255, 255, 204));
        AccButton.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        AccButton.setText("Acceuil");
        AccButton.setBorder(new javax.swing.border.MatteBorder(null));
        AccButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AccButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AccButtonStateChanged(evt);
            }
        });
        AccButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccButtonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AccButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AccButtonMouseReleased(evt);
            }
        });
        AccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccButtonActionPerformed(evt);
            }
        });

        gAdherButt.setBackground(new java.awt.Color(255, 255, 204));
        gAdherButt.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        gAdherButt.setText("gestion adhérant");
        gAdherButt.setToolTipText("");
        gAdherButt.setBorder(new javax.swing.border.MatteBorder(null));
        gAdherButt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gAdherButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gAdherButtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gAdherButtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gAdherButtMouseReleased(evt);
            }
        });
        gAdherButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gAdherButtActionPerformed(evt);
            }
        });

        statsButt.setBackground(new java.awt.Color(255, 255, 204));
        statsButt.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        statsButt.setText("statistique");
        statsButt.setToolTipText("");
        statsButt.setBorder(new javax.swing.border.MatteBorder(null));
        statsButt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statsButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statsButtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                statsButtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                statsButtMouseReleased(evt);
            }
        });
        statsButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsButtActionPerformed(evt);
            }
        });

        decButt.setBackground(new java.awt.Color(255, 255, 204));
        decButt.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        decButt.setText("déconnecter");
        decButt.setToolTipText("");
        decButt.setBorder(new javax.swing.border.MatteBorder(null));
        decButt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        decButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decButtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                decButtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                decButtMouseReleased(evt);
            }
        });
        decButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gDocButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AccButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gAdherButt, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(statsButt, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(decButt, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(AccButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gDocButt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gAdherButt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statsButt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(decButt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        main.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(main, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gDocButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gDocButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gDocButtActionPerformed

    private void AccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccButtonActionPerformed

    private void AccButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccButtonMouseClicked
        // TODO add your handling code here:
        AccButton.setBackground(Color.getColor("1E2D2F"));
        gDocButt.setBackground(Color.white);
        gAdherButt.setBackground(Color.white);
        statsButt.setBackground(Color.white);
        decButt.setBackground(Color.white);
        

    }//GEN-LAST:event_AccButtonMouseClicked
                              
  
    private void AccButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccButtonMouseReleased
        // TODO add your handling code here:
        AccButton.setForeground(Color.black);
        
    }//GEN-LAST:event_AccButtonMouseReleased

    private void AccButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AccButtonStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_AccButtonStateChanged

    private void gAdherButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gAdherButtActionPerformed
        // TODO add your handling code here:
        a.setVisible(true);
    }//GEN-LAST:event_gAdherButtActionPerformed

    private void statsButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statsButtActionPerformed

    private void decButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decButtActionPerformed

    private void AccButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccButtonMousePressed
        // TODO add your handling code here:
        AccButton.setForeground(Color.red);
    }//GEN-LAST:event_AccButtonMousePressed

    private void gDocButtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gDocButtMousePressed
        // TODO add your handling code here:
        gDocButt.setForeground(Color.red);
    }//GEN-LAST:event_gDocButtMousePressed

    private void gAdherButtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gAdherButtMousePressed
        // TODO add your handling code here:
        gAdherButt.setForeground(Color.red);
    }//GEN-LAST:event_gAdherButtMousePressed

    private void statsButtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsButtMousePressed
        // TODO add your handling code here:
        statsButt.setForeground(Color.red);
    }//GEN-LAST:event_statsButtMousePressed

    private void decButtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decButtMousePressed
        // TODO add your handling code here:
        decButt.setForeground(Color.red);
    }//GEN-LAST:event_decButtMousePressed

    private void gDocButtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gDocButtMouseReleased
        // TODO add your handling code here:
        gDocButt.setForeground(Color.BLACK);
    }//GEN-LAST:event_gDocButtMouseReleased

    private void gAdherButtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gAdherButtMouseReleased
        // TODO add your handling code here:
        gAdherButt.setForeground(Color.BLACK);
    }//GEN-LAST:event_gAdherButtMouseReleased

    private void statsButtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsButtMouseReleased
        // TODO add your handling code here:
        statsButt.setForeground(Color.BLACK);
    }//GEN-LAST:event_statsButtMouseReleased

    private void decButtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decButtMouseReleased
        // TODO add your handling code here:
        decButt.setForeground(Color.BLACK);
    }//GEN-LAST:event_decButtMouseReleased

    private void gDocButtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gDocButtMouseClicked
        // TODO add your handling code here:
        gDocButt.setBackground(Color.getColor("1E2D2F"));
        AccButton.setBackground(Color.white);
        gAdherButt.setBackground(Color.white);
        statsButt.setBackground(Color.white);
        decButt.setBackground(Color.white);
    }//GEN-LAST:event_gDocButtMouseClicked

    private void gAdherButtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gAdherButtMouseClicked
        // TODO add your handling code here:
        gAdherButt.setBackground(Color.getColor("1E2D2F"));
        gDocButt.setBackground(Color.white);
        AccButton.setBackground(Color.white);
        statsButt.setBackground(Color.white);
        decButt.setBackground(Color.white);
    }//GEN-LAST:event_gAdherButtMouseClicked

    private void statsButtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsButtMouseClicked
        // TODO add your handling code here:
        statsButt.setBackground(Color.getColor("1E2D2F"));
        gDocButt.setBackground(Color.white);
        gAdherButt.setBackground(Color.white);
        AccButton.setBackground(Color.white);
        decButt.setBackground(Color.white);
    }//GEN-LAST:event_statsButtMouseClicked

    private void decButtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decButtMouseClicked
        // TODO add your handling code here:
        decButt.setBackground(Color.getColor("1E2D2F"));
        gDocButt.setBackground(Color.white);
        gAdherButt.setBackground(Color.white);
        statsButt.setBackground(Color.white);
        AccButton.setBackground(Color.white);
    }//GEN-LAST:event_decButtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccButton;
    private javax.swing.JButton decButt;
    private javax.swing.JButton gAdherButt;
    private javax.swing.JButton gDocButt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane main;
    private javax.swing.JButton statsButt;
    // End of variables declaration//GEN-END:variables
}
